version: '3.8'

services:
  # SQL Server Database
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: lessionprm-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=LessionPRM@123
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - lessionprm-network

  # Spring Boot Application
  app:
    build: .
    container_name: lessionprm-backend
    depends_on:
      - sqlserver
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_USERNAME=sa
      - DB_PASSWORD=LessionPRM@123
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://sqlserver:1433;databaseName=LessionPRM;encrypt=false;trustServerCertificate=true
      - JWT_SECRET=mySecretKey12345678901234567890123456789012345678901234567890
      - MOMO_PARTNER_CODE=MOMOBKUN20180529
      - MOMO_ACCESS_KEY=klm05TvNBzhg7h7j
      - MOMO_SECRET_KEY=at67qH6mk8w5Y1nAyMoYKMWACiEi2bsa
      - MOMO_ENDPOINT=https://test-payment.momo.vn/v2/gateway/api/create
      - MOMO_REDIRECT_URL=http://localhost:3000/payment/success
      - MOMO_NOTIFY_URL=http://localhost:8080/api/payment/momo/callback
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,http://localhost:3001
    networks:
      - lessionprm-network
    restart: unless-stopped

volumes:
  sqlserver_data:

networks:
  lessionprm-network:
    driver: bridge