server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:sqlserver://database:1433;databaseName=LessionPRM;encrypt=true;trustServerCertificate=true}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:LessionPRM123!}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: false

  security:
    jwt:
      secret: ${JWT_SECRET:lessionprm-docker-secret-key-change-in-production}
      expiration: 86400000 # 24 hours
      refresh-expiration: 604800000 # 7 days

  # Mail configuration for Docker
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# MoMo Configuration for Docker
momo:
  partner-code: ${MOMO_PARTNER_CODE:MOMOBKUN20180529}
  access-key: ${MOMO_ACCESS_KEY:klm05TvNBzhg7h7j}
  secret-key: ${MOMO_SECRET_KEY:at67qH6mk8w5Y1nAyMoYKMWACiEi2bsa}
  endpoint: ${MOMO_ENDPOINT:https://test-payment.momo.vn/v2/gateway/api/create}
  redirect-url: ${MOMO_REDIRECT_URL:http://localhost:3000/payment/success}
  notify-url: ${MOMO_NOTIFY_URL:http://localhost:8080/api/payment/momo/callback}

# Logging for production
logging:
  level:
    com.lessionprm.backend: INFO
    org.springframework.security: WARN
    org.hibernate: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# OpenAPI Documentation
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized