server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: lession-prm-backend

  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=LessionPRM;encrypt=false;trustServerCertificate=true
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:password}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true
    defer-datasource-initialization: true

  security:
    user:
      name: admin
      password: admin

  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: NON_NULL

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:3001}
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /api-docs

jwt:
  secret: ${JWT_SECRET:mySecretKey12345678901234567890123456789012345678901234567890}
  expiration: 86400000
  refresh-expiration: 604800000

momo:
  partner-code: ${MOMO_PARTNER_CODE:MOMOBKUN20180529}
  access-key: ${MOMO_ACCESS_KEY:klm05TvNBzhg7h7j}
  secret-key: ${MOMO_SECRET_KEY:at67qH6mk8w5Y1nAyMoYKMWACiEi2bsa}
  endpoint: ${MOMO_ENDPOINT:https://test-payment.momo.vn/v2/gateway/api/create}
  redirect-url: ${MOMO_REDIRECT_URL:http://localhost:3000/payment/success}
  notify-url: ${MOMO_NOTIFY_URL:http://localhost:8080/api/payment/momo/callback}

logging:
  level:
    com.lessionprm: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
